// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_impute_knn_omp
NumericMatrix cpp_impute_knn_omp(NumericMatrix mat, int k, int n_threads);
RcppExport SEXP _mojpakiet_cpp_impute_knn_omp(SEXP matSEXP, SEXP kSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_impute_knn_omp(mat, k, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lof_omp
NumericVector cpp_lof_omp(NumericMatrix mat, int k, int n_threads);
RcppExport SEXP _mojpakiet_cpp_lof_omp(SEXP matSEXP, SEXP kSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lof_omp(mat, k, n_threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mojpakiet_cpp_impute_knn_omp", (DL_FUNC) &_mojpakiet_cpp_impute_knn_omp, 3},
    {"_mojpakiet_cpp_lof_omp", (DL_FUNC) &_mojpakiet_cpp_lof_omp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_mojpakiet(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
