# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_impute_knn_omp <- function(mat, k, n_threads) {
    .Call(`_mojpakiet_cpp_impute_knn_omp`, mat, k, n_threads)
}

cpp_lof_omp <- function(mat, k, n_threads) {
    .Call(`_mojpakiet_cpp_lof_omp`, mat, k, n_threads)
}

